### ISSUE TITLE
reuseport.Listen success on Darwin, but maybe not load balanced

### ISSUE THREAD

**Issue by hitzhangjie** [libp2p/go-reuseport#80]
Please check my testcase:
https://github.com/hitzhangjie/codemaster/tree/master/hot_restart

you can `go run main.go` to run the server, and `curl http://localhost:8080/hello` to see `Hello from $pid`.

then `kill -SIGUSR1 $pid` to notify it do a `fork`, parent and children processes reuseport.Listen successfully.

but `curl` always return the same $pid.

Only after I `kill -SIGTERM $1st-pid`, the 2nd listener works in the forked children process, 
then kill the 2nd forked process, then curl you'll see the 3rd forked process works.

**Comment by willscott** [comment]
i'm confused. you're using `os.StartProcess` rather than `syscall.ForkExec()` so the new process will start over rather than continuing from the same state.
As such, the new process will over-write the fd of the passed listener with a second call to listen re-using port. While the second bind will succeed, there isn't a guarantee of a shared queue from the OS in this scenario - you would need to have both processes be `accept()`'ing from a shared FD if you want balancing.

you can use startProcess as you are, but at the start of main, if you're the child don't run the re-use listen again and instead re-use the provided fd #4 as an existing listener.

**Comment by hitzhangjie** [comment]
@willscott Oh, Yes. Thank you for pointing out my mistake.👍🏻
